# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v2.1.1
      with:
        branch: "master"
        tag_prefix: "v"
        major_pattern: "(BC)"
        minor_patter: "(MC)"
        format: "${major}.${minor}.${patch}.${increment}"
        change_path: "src/"
      run: ./gradlew build
